// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    EvChart: typeof import('./src/components/common/EvChart/EvChart.vue')['default']
    EvChartAttr: typeof import('./src/components/EvChartAttr/EvChartAttr.vue')['default']
    EvChartFormItem: typeof import('./src/components/EvChartAttr/components/EvChartFormItem.vue')['default']
    EvChartItem: typeof import('./src/components/EvChartAttr/components/EvChartItem.vue')['default']
    EvChartTabItem: typeof import('./src/components/EvChartAttr/components/EvChartTabItem.vue')['default']
    EvChartTabs: typeof import('./src/components/EvChartAttr/components/EvChartTabs.vue')['default']
    EvCode: typeof import('./src/components/common/EvCode/EvCode.vue')['default']
    EvLoading: typeof import('./src/components/common/EvLoading/EvLoading.vue')['default']
    EvMenu: typeof import('./src/components/common/EvMenu/EvMenu.vue')['default']
    EvMenuItem: typeof import('./src/components/common/EvMenu/components/EvMenuItem.vue')['default']
    EvReq: typeof import('./src/components/common/EvReq/EvReq.vue')['default']
    EvTitle: typeof import('./src/components/common/EvTitle/EvTitle.vue')['default']
    EvVar: typeof import('./src/components/common/EvVar/EvVar.vue')['default']
    ReqTable: typeof import('./src/components/common/EvReq/components/ReqTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestCo: typeof import('./src/components/Test/TestCo.vue')['default']
    ToggleTheme: typeof import('./src/components/common/ToggleTheme/ToggleTheme.vue')['default']
  }
}
