export default [
  { id: 44,
    appName: '表单设计',
    appId: '2af076bc-9bae-4909-b6d3-83d583441d8d', 
    appType: 'app', 
    orderNum: 200,
    pid: '',
    icon: '',
    description: '', 
  },
  { id: 441,
    appName: '页面设计',
    appId: 'test', 
    appType: 'app', 
    orderNum: 200,
    pid: '',
    icon: '',
    description: '', 
  },
] as sysMenu[]